name: CI/CD for Spring Boot Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy mã nguồn từ GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cài đặt JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Build ứng dụng Spring Boot
      - name: Build Gradle Project
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      # 4. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/spring-demo-2 .

      # 5. Đăng nhập vào DockerHub
      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      # 6. Push Docker Image lên DockerHub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spring-demo-2

      - name: Debug AWS Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID starts with: ${AWS_ACCESS_KEY_ID:0:4}******"
          echo "AWS_SECRET_ACCESS_KEY starts with: ${AWS_SECRET_ACCESS_KEY:0:4}******"
          echo "AWS_SESSION_TOKEN starts with: ${AWS_SESSION_TOKEN:0:4}******"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      # 7. Kiểm tra AWS Credentials
      - name: Debug AWS Credentials
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'

      # 8. Kiểm tra quyền AWS ECS
      - name: Check AWS ECS Permissions
        run: aws ecs describe-clusters --clusters spring-demo-cluster-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'

      # 9. Deploy lên ECS
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster spring-demo-cluster-1 \
            --service spring-demo-service \
            --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'

      # 10. Thông báo thành công
      - name: Notify Success
        if: success()
        run: echo "Deployment Successful!"
